name: brave-test
recipe: wordpress
config:
  webroot: web
services:
  appserver:
    type: php:8.3

proxy:
  appserver_nginx:
    - brave.lndo.site
  mailpit:
    - mail.brave.lndo.site
  pma:
    - pma.brave.lndo.site